test ansible_host=50.0.0.10

pubserver ansible_host=50.0.0.240

[webs]
web1 ansible_host=50.0.0.101
web2 ansible_host=50.0.0.102
web3 ansible_host=50.0.0.103

[lvs]
lvs1 ansible_host=50.0.0.5
lvs2 ansible_host=50.0.0.6

[ceph]
ceph1 ansible_host=50.0.0.11
ceph2 ansible_host=50.0.0.12
ceph3 ansible_host=50.0.0.13

[sql]
sql1 ansible_host=50.0.0.250
sql2 ansible_host=50.0.0.251

[redis]
redis1 ansible_host=50.0.0.50
redis2 ansible_host=50.0.0.51
redis3 ansible_host=50.0.0.52
